# Generated by Django 2.2.12 on 2023-02-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20230210_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='colors',
            new_name='cardType',
        ),
        migrations.RenameField(
            model_name='format',
            old_name='color',
            new_name='requirements',
        ),
    ]
