# Generated by Django 2.2.12 on 2023-02-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20230209_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='setName',
            new_name='color',
        ),
    ]
